//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTesting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FluJabEntities2 : DbContext
    {
        public FluJabEntities2()
            : base("name=FluJabEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AssignmentStatus> tbl_AssignmentStatus { get; set; }
        public virtual DbSet<tblStaff> tblStaffs { get; set; }
        public virtual DbSet<tbl_Divisions> tbl_Divisions { get; set; }
        public virtual DbSet<tbl_Departments> tbl_Departments { get; set; }
        public virtual DbSet<tbl_Professions> tbl_Professions { get; set; }
        public virtual DbSet<tbl_DeclinedReasons> tbl_DeclinedReasons { get; set; }
        public virtual DbSet<tbl_Audit> tbl_Audit { get; set; }
        public virtual DbSet<tbl_StaffGroups> tbl_StaffGroups { get; set; }
        public virtual DbSet<tbl_FacingGroups> tbl_FacingGroups { get; set; }
        public virtual DbSet<tbl_HighRiskAreas> tbl_HighRiskAreas { get; set; }
        public virtual DbSet<tbl_Vaccinators> tbl_Vaccinators { get; set; }
        public virtual DbSet<tbl_AssignmentCats> tbl_AssignmentCats { get; set; }
        public virtual DbSet<tbl_VaccManus> tbl_VaccManus { get; set; }
        public virtual DbSet<tbl_VaccBatch> tbl_VaccBatch { get; set; }
        public virtual DbSet<tbl_HomeTesting> tbl_HomeTesting { get; set; }
    }
}
