//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Audit
    {
        public int AuditID { get; set; }
        public string EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public string VaccStatus { get; set; }
        public string VaccStatusBy { get; set; }
        public string VaccLocation { get; set; }
        public string VaccName { get; set; }
        public string VaccBatch { get; set; }
        public Nullable<System.DateTime> VaccDate { get; set; }
        public string DecReason { get; set; }
    }
}
