//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HomeTesting
    {
        public int HTId { get; set; }
        public string EmployeeNumber { get; set; }
        public bool TestingKitIssued { get; set; }
        public string LotNumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Ward { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
    }
}
