//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaff
    {
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeNumber { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string AssignmentStatus { get; set; }
        public string StaffGroup { get; set; }
        public string Role { get; set; }
        public string AssignmentCategory { get; set; }
        public string Paypoint { get; set; }
        public string CostCentre { get; set; }
        public string Profession { get; set; }
        public string VaccinationStatus { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public string VaccinationStatusBy { get; set; }
        public string VaccinationLocation { get; set; }
        public string VaccinatorName { get; set; }
        public Nullable<System.DateTime> VaccinatorDateTime { get; set; }
        public string VaccinationBatchNumber { get; set; }
        public string AddedByUser { get; set; }
        public Nullable<System.DateTime> DateAddedToDB { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string DeclinedReason { get; set; }
        public Nullable<bool> FrontLineStaff { get; set; }
        public Nullable<bool> AddedStaffToDB { get; set; }
        public Nullable<bool> ActiveStaff { get; set; }
        public string AnatomicalSiteOfVaccination { get; set; }
        public Nullable<bool> HighRisk { get; set; }
        public string HighRiskArea { get; set; }
        public string PatientFacingGroup { get; set; }
        public string VerbalConstent { get; set; }
        public Nullable<bool> AreYouWellToday { get; set; }
        public Nullable<bool> AllergicToEggs { get; set; }
        public Nullable<bool> Allergies { get; set; }
        public Nullable<bool> ProblemsFromAFluInjection { get; set; }
        public Nullable<bool> ConditionAffectingImmune { get; set; }
        public string VaccExpiryDate { get; set; }
        public string VaccManu { get; set; }
    }
}
